#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Knyazev Evgeniy
  description: Role to create a text file using custom module
  company: Your Company
  license: GPL-3.0-or-later
  min_ansible_version: "2.9"
  galaxy_tags: []
dependencies: []
